Securrency-OSS/mirai

README.md, packages/mirai/README.md, packages/mirai/example/README.md
The example README.md file is added to show the example in the pub.dev
=> Add example README.md file

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/example_request.md.dart, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
This PR will add the pull request and issue templates to make the contribution more seamless 😀
=> Add pull request and issues templates

.github/ISSUE_TEMPLATE/chore.md
This PR will add a chore issue template
=> Add the chore issue template.

examples/mirai_gallery/assets/json/example_light_theme.json, packages/mirai/lib/src/parsers/mirai_icon_theme_data/mirai_icon_theme_data.dart, packages/mirai/lib/src/parsers/mirai_icon_theme_data/mirai_icon_theme_data.freezed.dart, packages/mirai/lib/src/parsers/mirai_icon_theme_data/mirai_icon_theme_data.g.dart, packages/mirai/lib/src/parsers/mirai_offset/mirai_offset.dart, packages/mirai/lib/src/parsers/mirai_offset/mirai_offset.freezed.dart, packages/mirai/lib/src/parsers/mirai_offset/mirai_offset.g.dart, packages/mirai/lib/src/parsers/mirai_shadow/mirai_shadow.dart, packages/mirai/lib/src/parsers/mirai_shadow/mirai_shadow.freezed.dart, packages/mirai/lib/src/parsers/mirai_shadow/mirai_shadow.g.dart, packages/mirai/lib/src/parsers/mirai_theme/mirai_theme.dart, packages/mirai/lib/src/parsers/mirai_theme/mirai_theme.freezed.dart, packages/mirai/lib/src/parsers/mirai_theme/mirai_theme.g.dart
Add support for `iconTheme ` in `MiraiTheme`
Closes #90
=> feat: Add support for `iconTheme` in `MiraiTheme`

README.md, packages/mirai/CHANGELOG.md, packages/mirai/README.md, packages/mirai/pubspec.yaml
=> Mirai v0.1 release

docs/docs/overview.md, examples/mirai_gallery/lib/main.dart, packages/mirai/README.md, packages/mirai/lib/src/framework/mirai_app.dart
- Remove parser initialization from MiraiApp
- Wrap home in MiraiApp with a Builder
- Replace home with homeBuilder
=> fix: MiraiApp Fixes

examples/mirai_gallery/assets/json/center_example.json, examples/mirai_gallery/assets/json/home_screen.json, packages/mirai/lib/src/framework/mirai.dart, packages/mirai/lib/src/parsers/mirai_center/mirai_center.dart, packages/mirai/lib/src/parsers/mirai_center/mirai_center.freezed.dart, packages/mirai/lib/src/parsers/mirai_center/mirai_center.g.dart, packages/mirai/lib/src/parsers/mirai_center/mirai_center_parser.dart, packages/mirai/lib/src/utils/icon_utils.dart, packages/mirai/lib/src/utils/widget_type.dart
In this PR, I added a center mirai parser and added an example route for the center widget in the mirai gallery app.
NONE
=> Added Center widget

examples/mirai_gallery/assets/json/text_field_example.json, packages/mirai/lib/src/parsers/mirai_input_formatters/mirai_input_formatter.dart, packages/mirai/lib/src/parsers/mirai_input_formatters/mirai_input_formatter.freezed.dart, packages/mirai/lib/src/parsers/mirai_input_formatters/mirai_input_formatter.g.dart, packages/mirai/lib/src/parsers/mirai_text_field/mirai_text_field.dart, packages/mirai/lib/src/parsers/mirai_text_field/mirai_text_field.freezed.dart, packages/mirai/lib/src/parsers/mirai_text_field/mirai_text_field.g.dart, packages/mirai/lib/src/parsers/mirai_text_field/mirai_text_field_parser.dart, packages/mirai/lib/src/parsers/mirai_text_form_field/mirai_text_form_field.dart, packages/mirai/lib/src/parsers/mirai_text_form_field/mirai_text_form_field.freezed.dart, packages/mirai/lib/src/parsers/mirai_text_form_field/mirai_text_form_field.g.dart, packages/mirai/lib/src/parsers/mirai_text_form_field/mirai_text_form_field_parser.dart, packages/mirai/lib/src/parsers/parsers.dart, packages/mirai/lib/src/utils/input_formatters.dart
… in text fields.
Added `inputFormatters` support  in `Mirai` `TextField` and `TextFormField`
Closes #109
=> feat: Added `inputFormatters` support  in `Mirai` `TextField` and `TextFormField`

examples/mirai_gallery/assets/json/home_screen.json
Removed align in home screen JSON as it doesn't take effect.
Closes #115
=> fix: Removed align in home screen json

packages/mirai/lib/src/parsers/mirai_bottom_app_bar_theme/mirai_bottom_app_bar_theme.dart, packages/mirai/lib/src/parsers/mirai_bottom_app_bar_theme/mirai_bottom_app_bar_theme.freezed.dart, packages/mirai/lib/src/parsers/mirai_bottom_app_bar_theme/mirai_bottom_app_bar_theme.g.dart, packages/mirai/lib/src/parsers/mirai_theme/mirai_theme.dart, packages/mirai/lib/src/parsers/mirai_theme/mirai_theme.freezed.dart, packages/mirai/lib/src/parsers/mirai_theme/mirai_theme.g.dart, packages/mirai/lib/src/parsers/parsers.dart
Add support for `bottomAppBarTheme` in `MiraiTheme`
Closes #126
=> feat: Add support for `bottomAppBarTheme` in `MiraiTheme`

examples/mirai_gallery/assets/json/text_example.json, packages/mirai/lib/src/parsers/mirai_text/mirai_text.dart, packages/mirai/lib/src/parsers/mirai_text/mirai_text.freezed.dart, packages/mirai/lib/src/parsers/mirai_text/mirai_text.g.dart, packages/mirai/lib/src/parsers/mirai_text/mirai_text_parser.dart
Add support to rich text functionality in Mirai Text.
closes #152
=> feat: Extending rich text functionality to Mirai Text.

packages/mirai/lib/src/parsers/mirai_elevated_button/mirai_elevated_button_parser.dart, packages/mirai/lib/src/parsers/mirai_expanded/mirai_expanded.dart, packages/mirai/lib/src/parsers/mirai_expanded/mirai_expanded.freezed.dart, packages/mirai/lib/src/parsers/mirai_expanded/mirai_expanded.g.dart, packages/mirai/lib/src/parsers/mirai_expanded/mirai_expanded_parser.dart, packages/mirai/lib/src/parsers/parsers.dart, packages/mirai/lib/src/utils/widget_type.dart
This PR adds support for the expanded widget in Mirai
closes #163
=> feat: Mirai Expanded Parser

packages/mirai/lib/src/framework/mirai.dart, packages/mirai/lib/src/parsers/mirai_flexible/mirai_flexible.dart, packages/mirai/lib/src/parsers/mirai_flexible/mirai_flexible.freezed.dart, packages/mirai/lib/src/parsers/mirai_flexible/mirai_flexible.g.dart, packages/mirai/lib/src/parsers/mirai_flexible/mirai_flexible_parser.dart, packages/mirai/lib/src/parsers/parsers.dart, packages/mirai/lib/src/utils/widget_type.dart
Add support to `Flexible` widget, allowing us to use the text ellipsis inside `Row` widgets.
=> feat: Add support to `Flexible` widget

packages/mirai/lib/src/parsers/mirai_input_border/mirai_input_border.dart
=> Add InputBorder.none

examples/mirai_gallery/assets/json/text_example.json, examples/mirai_gallery/pubspec.lock, packages/mirai/lib/src/parsers/mirai_text/mirai_text.dart, packages/mirai/lib/src/parsers/mirai_text/mirai_text.freezed.dart, packages/mirai/lib/src/parsers/mirai_text/mirai_text.g.dart, packages/mirai/lib/src/parsers/mirai_text/mirai_text_parser.dart
Add tap gesture recognizer to the Mirai text Span
=> feat: Add tap gesture recognizer to the Mirai text Span

packages/mirai/CHANGELOG.md, packages/mirai/pubspec.yaml
=> chore: Update Mirai to v0.5

docs/docs/basics/actions.md, examples/mirai_gallery/assets/json/dialog_example.json, examples/mirai_gallery/assets/json/home_screen.json, examples/mirai_gallery/assets/json/navigation_example.json, examples/mirai_gallery/assets/json/text_example.json
Removed unwanted type "navigationType" in example JSON
#202
=> chore: Removed unwanted type "navigationType" in example jsons

packages/mirai/README.md, packages/mirai_framework/README.md, packages/mirai_framework/example/README.md, packages/mirai_framework/pubspec.yaml
Added readme for mirai_framework
=> Added readme for mirai_framework

examples/mirai_gallery/assets/json/home_screen.json, examples/mirai_gallery/assets/json/sign_in_screen.json, examples/mirai_gallery/assets/json/user_profile_screen.json, examples/mirai_gallery/lib/app/home/home_screen.dart, packages/mirai/lib/src/action_parsers/mirai_network_request/mirai_network_request.dart, packages/mirai/lib/src/action_parsers/mirai_network_request/mirai_network_request.freezed.dart, packages/mirai/lib/src/action_parsers/mirai_network_request/mirai_network_request.g.dart, packages/mirai/lib/src/action_parsers/mirai_network_request/mirai_network_request_parser.dart, packages/mirai/lib/src/action_parsers/mirai_network_result/mirai_network_result.dart, packages/mirai/lib/src/action_parsers/mirai_network_result/mirai_network_result.freezed.dart, packages/mirai/lib/src/action_parsers/mirai_network_result/mirai_network_result.g.dart
Added `MiraiNetworkResult` type in mirai/network_request to handle different statuses of an api response
=> feat: Added `MiraiNetworkResult` type in mirai/network_request to handle different statuses

packages/mirai/lib/mirai.dart
=> Exported `services` in mirai framework

packages/mirai/lib/src/services/mirai_network_service.dart
Updated form request body to handle `Files`
Let's say if we want to use it in app using `Mirai`: 
```
MiraiNetworkRequest(
url: "YOUR_URL",
method: REQUEST_METHOD,
body: {
"file": FILE_OBJECT,
},
);
```
=> feat: Updated form request body to handle `Files`

examples/mirai_gallery/assets/json/sign_in_screen.json, packages/mirai/lib/src/action_parsers/mirai_network_request/mirai_network_request_parser.dart, packages/mirai/lib/src/services/mirai_network_service.dart
Returning `formdata` in body construction for multi-part post requests in Mirai network service
=> feat: Returning `formdata` in body construction for multi-part post requests in Mirai network service

examples/mirai_gallery/pubspec.lock, packages/mirai/lib/src/utils/utils.dart
Added scroll physics export statement in utils.dart
=> fix: Added scroll physics export statement in utils.dart

examples/mirai_gallery/assets/json/home_screen.json, examples/mirai_gallery/assets/json/wrap_example.json, packages/mirai/lib/src/framework/mirai.dart, packages/mirai/lib/src/parsers/mirai_wrap/mirai_wrap.dart, packages/mirai/lib/src/parsers/mirai_wrap/mirai_wrap.freezed.dart, packages/mirai/lib/src/parsers/mirai_wrap/mirai_wrap.g.dart, packages/mirai/lib/src/parsers/mirai_wrap/mirai_wrap_parser.dart, packages/mirai/lib/src/parsers/parsers.dart, packages/mirai/lib/src/utils/widget_type.dart
This PR adds support to the Wrap widget.
Closes #271
=> feat: Add support to the Wrap widget

examples/mirai_gallery/macos/Flutter/GeneratedPluginRegistrant.swift, examples/mirai_gallery/pubspec.lock, packages/mirai/lib/src/parsers/mirai_image/mirai_image_parser.dart, packages/mirai/pubspec.yaml
+ `cached_network_image` as a dependency in package's `pubspec.yaml`
+ Replace `Image.network` with `CachedNetworkImage`
Closes #255
=> feat: Replaced `Image.network` with `CachedNetworkImage`

examples/mirai_gallery/assets/json/home_screen.json, examples/mirai_gallery/assets/json/table_example.json, packages/mirai/lib/src/framework/mirai.dart, packages/mirai/lib/src/parsers/mirai_table/mirai_table.dart, packages/mirai/lib/src/parsers/mirai_table/mirai_table.freezed.dart, packages/mirai/lib/src/parsers/mirai_table/mirai_table.g.dart, packages/mirai/lib/src/parsers/mirai_table/mirai_table_parser.dart, packages/mirai/lib/src/parsers/mirai_table_cell/mirai_table_cell.dart, packages/mirai/lib/src/parsers/mirai_table_cell/mirai_table_cell.freezed.dart, packages/mirai/lib/src/parsers/mirai_table_cell/mirai_table_cell.g.dart, packages/mirai/lib/src/parsers/mirai_table_cell/mirai_table_cell_parser.dart, packages/mirai/lib/src/parsers/parsers.dart, packages/mirai/lib/src/utils/widget_type.dart
This PR adds support for the Table widget in Mirai.
Closes #272
=> feat: Add Mirai Table Parser
